In [1]:
import numpy as np

In [18]:
M = np.random.randn(2,2)
zero = np.zeros((1,2))
sqrt_alpha = np.array([1]).reshape(1,1)
v_over_alpha = np.random.randn(2,1)


In [19]:
v_over_alpha, M

(array([[-1.78212652],
        [-0.59768578]]),
 array([[-1.06464077, -1.46502892],
        [ 1.13123502, -1.3128215 ]]))

In [20]:
sqrt_alpha, zero

(array([[1]]), array([[0., 0.]]))

In [30]:

above = np.hstack((sqrt_alpha, zero))
bottom = np.hstack((v_over_alpha, M))

In [31]:
above

array([[1., 0., 0.]])

In [32]:
bottom

array([[-1.78212652, -1.06464077, -1.46502892],
       [-0.59768578,  1.13123502, -1.3128215 ]])

In [33]:
np.vstack((above, bottom))

array([[ 1.        ,  0.        ,  0.        ],
       [-1.78212652, -1.06464077, -1.46502892],
       [-0.59768578,  1.13123502, -1.3128215 ]])